---
abstract: 'Check the presence of tabs in your project'
author:
  - 'Tomas Doran <bobtfish@bobtfish.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.910'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-NoTabs
no_index:
  directory:
    - inc
    - t
requires:
  File::Find: 0
  File::Spec: 0
  FindBin: 0
  Test::Builder: 0
  Test::More: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bobtfish/perl-test-notabs.git
version: 1.0
